### PR TITLE
Remove charged terminology

### PR DESCRIPTION
**Pull request by grumpyoldman-io**
Hi there,
 
I'm opening this PR as a suggestion, to remove racially-charged and marginalizing terminology; according to the Code Of Conduct:
> In the interest of fostering an open and welcoming environment, we as
contributors and maintainers pledge to making participation in our project and
our community a harassment-free experience for everyone, regardless of age, body
size, disability, ethnicity, sex characteristics, gender identity and expression,
level of experience, education, socio-economic status, nationality, personal
appearance, race, religion, or sexual identity and orientation.

I think it would be great to take a step and take the following three (minor) changes:

1. Replace "master" branch with "main" branch as the default branch. (this PR)
2. Add "other" to gender options (perhaps staying away from gender in the docs is even better) (other PR: https://github.com/react-hook-form/documentation/pull/379)
3. Sort gender options alphabetically (other PR: https://github.com/react-hook-form/documentation/pull/379)

This PR would require that React-Hook-Form also switches from "master" to "main". I've opened a PR for that as well:
https://github.com/react-hook-form/react-hook-form/pull/2268

Related:
https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

### CODE REVIEW

**Comment by bluebill1049** [comment]
Thanks for the PR! I don't think `main` works tho.

**Comment by bluebill1049** [comment]
eg: https://github.com/react-hook-form/documentation/edit/main/src/data/home.tsx

**Comment by grumpyoldman-io** [comment]
@bluebill1049 That is because react-hook-form itself does not (yet) have a main branch. The following steps can be taken to achieve that:

1. Review and approve https://github.com/react-hook-form/react-hook-form/pull/2268
2. rename master to main (`git checkout -b main` and `git push --set-upstream origin $(git_current_branch)`)
3. validate and merge this PR.

**Comment by bluebill1049** [comment]
thanks, @grumpyoldman-io shall we do that the "master" part later?

**Comment by grumpyoldman-io** [comment]
I can split up the PR if you want, give me a sec.

**Comment by bluebill1049** [comment]
> I can split up the PR if you want, give me a sec.

Yes, please 🙏 many thanks let's sort out the gender first.

**Comment by grumpyoldman-io** [comment]
@bluebill1049 

I've created two PR's:
documentation: https://github.com/react-hook-form/documentation/pull/379
react-hook-form: https://github.com/react-hook-form/react-hook-form/pull/2269

Here is a how-to to change the default branch name:
https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by grumpyoldman-io** [comment]
@bluebill1049 This on is also now targeted towards the `main` branch

**Comment by bluebill1049** [comment]
thanks, I will sort it out this weekend or early next week 👍

**Comment by pmaier983** [comment]
Hey guys! Fully support the move from master -> main, but as I was just reading GitHub is planning on releasing support for this transformation [in the near future](https://github.com/github/renaming), and actually [recommends waiting](https://github.com/github/renaming/blob/main/README.md#now-supporting-early-movers-) until their work is done before changing.

I suggest we archive this PR and wait for added support form github!

Thanks for all the hard work grumpyoldman-io 😄

**Comment by bluebill1049** [comment]
> Hey guys! Fully support the move from master -> main, but as I was just reading GitHub is planning on releasing support for this transformation [in the near future](https://github.com/github/renaming), and actually [recommends waiting](https://github.com/github/renaming/blob/main/README.md#now-supporting-early-movers-) until their work is done before changing.
> 
> I suggest we archive this PR and wait for added support form github!
> 
> Thanks for all the hard work grumpyoldman-io 😄

That would be awesome!

**Comment by pmaier983** [comment]
Closing this PR until [github releases support](https://github.com/github/renaming)

**Pull request closed without merging**
