### PR TITLE
Examples: use new Joi version

### PR DESCRIPTION
**Pull request by jorisre**
Related to https://github.com/react-hook-form/resolvers/issues/79

I'm not the owner of codesanbox examples,  if someone could update it too :)

### CODE REVIEW

**Comment by pmaier983** [comment]
hey @jorisre Welcome to the team 😄. is the import the only change required? or is the a WIP?

**Comment by jorisre** [comment]
> hey @jorisre Welcome to the team 😄. is the import the only change required? or is the a WIP?

Hey @pmaier983 :) 
Thanks !

It's related to https://github.com/react-hook-form/resolvers/issues/79
That's why I've updated examples and yes only the import change

**Review by pmaier983 — APPROVED** [review]
LGTM!

**Comment by bluebill1049** [comment]
Thanks, guys. I will publish an update and then merge this doc in. also i will do the changeset in that repo as well, so everyone can publish.

**Comment by bluebill1049** [comment]
almost forgot to merge this one. thanks @jorisre 🙏

**Pull request merged**
