### PR TITLE
include ie11 info

### PR DESCRIPTION
**Pull request by bluebill1049**
related to : https://github.com/react-hook-form/react-hook-form/pull/2551/files

### CODE REVIEW

**Comment by pmaier983** [comment]
The lighthouse test is a bit flakey. I'll increase its timeout.

**Comment by bluebill1049** [comment]
would be nice if the lighthouse can produce a report, like some of the action that we using in the core lib.

**Comment by pmaier983** [comment]
Actually Lighthouse seems to be failing at the build step... Mb it was a fluke. If this issue: (`Error: Cannot find module 'gatsby-cli/lib/reporter'`) shows up again I'll have to fix the action.

**Comment by pmaier983** [comment]
It actually does create a report! Its just hidden in the github action log. 
Screen Shot 2020-08-11 at 9 48 34 PM
The links expire quickly though, but you can provide a server to store them. This is a plan of mine down the road!

**Pull request merged**
