### PR TITLE
Fix Formik code example to include error messages and apples-to-apples validation

### PR DESCRIPTION
**Pull request by jaredpalmer**

### CODE REVIEW

**Comment by pmaier983** [comment]
Thank you for the contribution Jared. We love the work you did on Formik! I'll leave this one for bill to review 😄.

**Comment by jaredpalmer** [comment]
Ping.

**Comment by bluebill1049** [comment]
Thanks, @jaredpalmer for the PR (updated Formik code) and also Formik :) I have been busy over the week and hence with the delay of response. Thanks for your patient. I am planning to change the "code comparison" to something else, as today react hook form is growing and it's confident enough to be its own, so I will sort out the section.

**Comment by jaredpalmer** [comment]
Would really appreciate you accept this PR or remove Formik from your comparison immediately as your are not fairly representing it.

**Comment by bluebill1049** [comment]
We are replacing the code comparison section with this PR: https://github.com/react-hook-form/documentation/pull/461

Before I close this issue, just to make sure it clear and transparent to everyone :) 

We are not intended to have an unfair representation of other libraries. In fact, both code snippets were copied from the official documentation from other libraries when RHF was created. I am obviously biased towards RHF, hence creating such a section and potential showcase its strength. 
 
Screen Shot 2020-11-16 at 9 08 17 am

Thanks for your PR.

**Pull request closed without merging**
