### PR TITLE
chore: enhance get-start chinese

### PR DESCRIPTION
**Pull request by cpprookie**
Enhance and sync get-start part chinese version. Major change points includes: 

- chinese terms
   - *Uncontrolled component*  `不受控制的组件` to `非受控组件` based on react chinese doc and chinese community usage.
    -  *validation* `验证` to `校验` based on ant-design usage.
    - *external ui libraries* `外部ui组件库` to `第三方ui组件库` based on chinese community usage.

- Sync current en docs, and correct some links with `translateLink`.
- change something to make it easier to understand in chinese.

### CODE REVIEW

**Comment by pmaier983** [comment]
This looks awesome cpprookie! Thank you for translating and syncing the docs!

**Comment by bluebill1049** [comment]
Screen Shot 2020-07-06 at 8 58 31 am

Looks like a missing closing tag :) Thanks for the contribution ❤️

**Comment by cpprookie** [comment]
> This looks awesome cpprookie! Thank you for translating and syncing the docs!

It's my pleasure that i can do something for comminity. I love you guys' amazing work.

**Comment by cpprookie** [comment]
> Screen Shot 2020-07-06 at 8 58 31 am
> 
> Looks like a missing closing tag :) Thanks for the contribution ❤️

ooops! A silly mistake. I  will update this pr.

**Comment by bluebill1049** [comment]
Thank you! merging.

**Comment by cpprookie** [comment]
> Thank you! merging.

I noticed that  v6.0 has released and i will try my best to keep translating other parts on chinese version in spare time.

**Comment by bluebill1049** [comment]
> > Thank you! merging.
> 
> I noticed that v6.0 has released and i will try my best to keep translating other parts on chinese version in spare time.

Amazing! no rush! Take your time, please. 非常感谢！

**Pull request merged**
