### PR TITLE
docs(dirty): finish dirty => isDirty migration in docs

### PR DESCRIPTION
**Pull request by vvo**
There were still a few places where we used "dirty" instead of "isDirty" for the
form state.

Let me know if that's ok. Thanks!

### CODE REVIEW

**Comment by bluebill1049** [comment]
hey, @vvo thanks for the help! ❤️ could you please exclude V5 folder? in v5 it's actually just`dirty`.

**Comment by vvo** [comment]
Ah sorry I had done that but some modifications still made it through :D Let me fix it now.

**Comment by vvo** [comment]
Ok, done

**Comment by bluebill1049** [comment]
awesome! thanks a lot 👍

**Pull request merged**
