### PR TITLE
feat: adding formstate, register, setvalue + minor bug fixes

### PR DESCRIPTION
**Pull request by aranlucas**
1. Adding formstate, register, setvalue pages to MDX
    * There were  some complicated tables that stayed in html. These can be addressed or simplified in the future.
    * setValue example -> sanbdox https://codesandbox.io/s/react-hook-form-v7-setvalue-h8wbk is a broken link. Didn't add in this PR
2. Fixed remaining issues with docs#controller functionality to just point to the actual page instead of waiting for a redirect on /docs page. There's no more /docs#something links in code base.
3. Updated dependencies which included a prettier upgrade (adding commas to the end)
4. Removed some any usages by just importing API file directly.
5. Added some ts-expect-errors since there's only 5 of them now and can be enabled on build

* https://react-hook-form-website-git-fork-aranlucas-lastdocs-hook-form.vercel.app/docs/useform/formstate
* https://react-hook-form-website-git-fork-aranlucas-lastdocs-hook-form.vercel.app/docs/useform/register
* https://react-hook-form-website-git-fork-aranlucas-lastdocs-hook-form.vercel.app/docs/useform/setvalue

### CODE REVIEW

**Comment by aranlucas** [comment]
@bluebill1049 Need help looking at logs.

I think it's related to https://github.com/contentlayerdev/contentlayer/issues/506

**Comment by bluebill1049** [comment]
image

I think you can run a local build as well.

**Comment by aranlucas** [comment]
I think I should have changed the log now. Can you check 1 more time :pray: ? 

I deleted node_modules and did a clean install, but I can't seem to repro the next one

**Comment by bluebill1049** [comment]
sorry for missing the pr review. 🙏  approved

**Review by bluebill1049 — APPROVED** [review]

**Pull request closed without merging**
