### PR TITLE
Docs(useForm/reset): edit options section & add values type

### PR DESCRIPTION
**Pull request by developer-bandi**
I performed the following two tasks.

1. Since values ​​can receive not only objects but also functions that accept objects as arguments, i added function type
2.Option properties at the same level as values ​​are lower levels of options (like setFocus docs), so i modify to suit the level.

### CODE REVIEW

**Review by bluebill1049 — APPROVED** [review]

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
Thanks for the contribution!

**Comment by bluebill1049** [comment]
@developer-bandi could you do a format with your PR? thanks

**Comment by developer-bandi** [comment]
@bluebill1049 i didn't understand format the pr. Can you explain more detail?

**Comment by bluebill1049** [comment]
> @bluebill1049 i didn't understand format the pr. Can you explain more detail? 

Check the ci build, just need to rerun prettier

**Comment by developer-bandi** [comment]
thank you. i fix and merge it

**Review by bluebill1049 — APPROVED** [review]

**Pull request merged**
