### PR TITLE
Adding new MDX pages - get started, use form, advanced, ts

### PR DESCRIPTION
**Pull request by aranlucas**
Adding new pages to MDX
* get started
* use form
* advanced
* ts

Contentious changes:
* use-form page is different than before. No more header underline under some areas.
* I tried to use the least amount of components/styling needed. Even if it isn't consistent right now, they eventually will all be.

Misc
* Fixing type errors caused by CSS modules - tsc was nearly useless with 600+ errors. Now: Found 27 errors in 9 files.

### CODE REVIEW

**Comment by bluebill1049** [comment]
> Need help with 👀 at the build logs when you get a chance. Smaller PR to review #965 and this can be rebased

what's the issue with build logs?

**Comment by bluebill1049** [comment]
image

**Comment by aranlucas** [comment]
If you're not part of the Vercel team, you can't access the build logs.

Thanks for the screenshot, that should help me fix it.

**Comment by bluebill1049** [comment]
Could you resolve those conflicst 🙏

**Comment by aranlucas** [comment]
This is ready. Let me know because I have another PR ready that's pretty  large again 😟

**Comment by bluebill1049** [comment]
I will come to those during the weekend 👍

**Comment by aranlucas** [comment]
FYI, I created sneak peak of next PR for you to start taking a look at https://github.com/aranlucas/documentation/pull/1 in case I can't submit PR in time after this one merges.

Sorry for the large commits, they should hopefully start getting smaller as more MDX migrations happen.

**Comment by bluebill1049** [comment]
Screenshot 2023-06-11 at 9 14 44 pm
973c8211998">

a bit of styling regression on the new build

**Comment by aranlucas** [comment]
I wanted to avoid having to do having to add styles https://github.com/react-hook-form/documentation/blob/master/src/styles/table.module.css but if it's a blocker I can add. It didn't bother me too much since it would be consistent later on.

It's a matter of adding table th and tr to MDX components similar to https://github.com/shadcn/taxonomy/blob/main/components/mdx-components.tsx#L103

Anything else that you would want to see changed?

**Comment by bluebill1049** [comment]
Got it, that's fine. I will do some more double check on the UI consistency. 👍

**Comment by aranlucas** [comment]
FYI, I played around with using https://tailwindcss.com/docs/typography-plugin as the styling. It looked pretty good but until everything is in markdown it looked out of place

**Comment by aranlucas** [comment]
> Got it, that's fine. I will do some more double check on the UI consistency. 👍

Can you try using the vercel comments? Never tried it before but it should make comments easier to address

**Comment by aranlucas** [comment]
https://github.com/react-hook-form/documentation/pull/973/commits/3f6ec98db795a1959c3cf73b732b4dbb353df1d6


This is what the change would look like if I cherry picked it into this branch. You can check that PR preview link that has more pages migrated and the "Consistency" starts being more and more and maintaining exact styles is less and less important.

One thing I have not been able to do is migrate tables with code in the table. I didn't want to resort to writing markdown tables, but it seems that's the only way if I wanted to maintain that.

**Review by bluebill1049 — APPROVED** [review]

**Pull request merged**
