### PR TITLE
Adds note about shouldUnregister: false to Modal/Tab FAQ

### PR DESCRIPTION
**Pull request by Slapbox**

### CODE REVIEW

**Comment by Slapbox** [comment]
@bluebill1049 thanks for your help with this! Let me know if you think the wording could be improved. I tried linking to the relevant are in the API documentation but the heading for the option doesn't have an `id` to reference in a URL.

**Comment by bluebill1049** [comment]
ty mate 👍

**Comment by Slapbox** [comment]
I actually missed the closing `</p>` hang on

**Comment by bluebill1049** [comment]
all good, sorted.

**Pull request merged**
