### PR TITLE
feat: migrating to nextjs

### PR DESCRIPTION
**Pull request by aranlucas**
https://nextjs.org/docs/migrating/from-gatsby

Move all gatsby links to nextjs links
Removed all gatsby packages
Renamed api --> docs since it's a reserved namespace for nextjs
Added CSS variables rather than relying on "lightMode". https://github.com/pacocoursey/next-themes#avoid-hydration-mismatch . Probably where I will need guidance, as my CSS -foo isn't the best (but there are no hydration mismatches or flashes!)

### CODE REVIEW

**Comment by aranlucas** [comment]
TODO: I don't think I understand Nav too well unfortunately. 

I need to find a way to separate Desktop Nav vs Mobile nav since I get them confused so easily

**Comment by aranlucas** [comment]
I could make this even simpler by doing the rename from api -> docs while gatsby is still default. Might focus the dark theme issues more than now

**Comment by aranlucas** [comment]
@bluebill1049 can you please approve the deployment? 

Fixed up the dark mode issues (that I saw) using global(".dark") and global(".light") CSS modules and I think it's looking pretty good.

Just want to verify from non-dev machine.

Thanks

**Comment by bluebill1049** [comment]
works great with dark mode 👍

**Comment by bluebill1049** [comment]
I will review it this week and merge it in.

**Comment by aranlucas** [comment]
Let me know if there's anything I need to address. I see that I need to fix light mode select in API page.

**Review by bluebill1049 — APPROVED** [review]

**Pull request merged**
