### PR TITLE
feat: moving to nextjs

### PR DESCRIPTION
**Pull request by aranlucas**
Feel free to reject if this is not wanted. This was a mostly an educative experience for me as I saw there was interest in https://github.com/react-hook-form/documentation/pull/750#issuecomment-1074931329

From my testing, everything is working as expected.

This PR has 1 controversial change moving /api to /docs since /api is reserved in NextJS.

Used next-themes to simplify some of the classNames for dark/light theme.

Used next-localization to simplify language (This can further be expanded with https://nextjs.org/docs/advanced-features/i18n-routing

```
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (84/84)
info  - Finalizing page optimization

Route (pages)                              Size     First Load JS
┌ ○ /                                      11.8 kB         159 kB
├   └ css/b7f5e89d5320a6c1.css             3.62 kB
├   /_app                                  0 B            86.2 kB
├ ○ /404                                   352 B           103 kB
├   └ css/592400813383cf4a.css             1.65 kB
├ ○ /about-us                              4.32 kB         107 kB
├   └ css/75af6facd326ddc2.css             3.56 kB
├ ○ /advanced-usage                        11.4 kB         125 kB
├ ○ /dev-tools                             23.6 kB         165 kB
├   └ css/dc13500c2b23ad2f.css             4.51 kB
├ ○ /docs                                  1.89 kB         131 kB
├   └ css/a53db50d4f6b119d.css             1.33 kB
├ ○ /docs/formprovider                     4.45 kB         114 kB
├ ○ /docs/usecontroller                    2.24 kB         134 kB
├   └ css/1a24dcefce28bcc3.css             1.15 kB
├ ○ /docs/usecontroller/controller         1.92 kB         133 kB
├ ○ /docs/usefieldarray                    5.34 kB         134 kB
├ ○ /docs/useform                          6.84 kB         135 kB
├   └ css/b94db0100f612791.css             1.33 kB
├ ○ /docs/useform/clearerrors              2.04 kB         131 kB
├ ○ /docs/useform/control                  2 kB            131 kB
├ ○ /docs/useform/form                     3.71 kB         117 kB
├   └ css/469069d2e367f33a.css             1.05 kB
├ ○ /docs/useform/formstate                2.21 kB         133 kB
├ ○ /docs/useform/getfieldstate            6.18 kB         116 kB
├   └ css/a8b08f05a16f15d1.css             899 B
├ ○ /docs/useform/getvalues                2.22 kB         131 kB
├ ○ /docs/useform/handlesubmit             2.51 kB         131 kB
├ ○ /docs/useform/register                 5.6 kB          134 kB
├   └ css/4ba3ec25ce67451e.css             1.16 kB
├ ○ /docs/useform/reset                    3.36 kB         132 kB
├ ○ /docs/useform/resetfield               3.1 kB          116 kB
├ ○ /docs/useform/seterror                 2.88 kB         132 kB
├ ○ /docs/useform/setfocus                 1.96 kB         131 kB
├ ○ /docs/useform/setvalue                 2.72 kB         131 kB
├ ○ /docs/useform/trigger                  2.41 kB         131 kB
├ ○ /docs/useform/unregister               3.09 kB         132 kB
├ ○ /docs/useform/watch                    3.58 kB         132 kB
├ ○ /docs/useformcontext                   2.15 kB         131 kB
├ ○ /docs/useformstate                     1.86 kB         132 kB
├ ○ /docs/useformstate/errormessage        2.69 kB         131 kB
├ ○ /docs/usewatch                         3.59 kB         132 kB
├ ○ /faqs                                  8.95 kB         122 kB
├   └ css/e0a7f14ad20406e8.css             595 B
├ ○ /form-builder                          341 B           144 kB
├   └ css/0b14ab262faeac55.css             4.79 kB
├ ○ /get-started                           8.56 kB         122 kB
├   └ css/c68e59e9195ef58b.css             342 B
├ ○ /media                                 1.77 kB         104 kB
├   └ css/53730f1a362960d5.css             3.67 kB
├ ○ /migrate-v6-to-v7                      308 B          86.5 kB
├ ○ /resources/3rd-party-bindings          489 B           124 kB
├ ○ /resources/articles                    485 B           124 kB
├ ○ /resources/newsletters                 481 B           124 kB
├ ○ /resources/videos                      479 B           124 kB
└ ○ /ts                                    6.08 kB         119 kB
+ First Load JS shared by all              90.1 kB
  ├ chunks/framework-3671d8951bf44e4e.js   45.2 kB
  ├ chunks/main-abae530378ed5c02.js        37.1 kB
  ├ chunks/pages/_app-9618934e7bcbd203.js  3.06 kB
  ├ chunks/webpack-edd86ecd947b1f44.js     837 B
  └ css/e67e953385824197.css               3.92 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)

```

### CODE REVIEW

**Comment by bluebill1049** [comment]
oh wow, did you really convert the whole site into Nextjs? cc @jorisre

**Comment by jorisre** [comment]
Oh wow ! 👏🏻 Seems working! I'll have a look later. Thanks a ton !

**Comment by aranlucas** [comment]
It really wasn't that bad moving to NextJS following https://nextjs.org/docs/migrating/from-gatsby

I'm pretty confident with the functionality working, but I'll be honest the CSS/ dark theme is probably going to get me in trouble and will probably require a bit of extra attention.

I also introduced a i18n to remove some files like https://github.com/react-hook-form/documentation/blob/51022f756c16e9e10dbf6e09238ef5a59f38e5f2/src/data/home.tsx

There's an auto extractor that will eventually remove all the hard coded text and translation effort can be done. ChatGPT does a decent job at least in Spanish with the prompt

```
can you translate the following strings to Spanish? just the keys
```

**Comment by bluebill1049** [comment]
Would be dream come true if we have some sort of auto-translate, this is something people miss the most from the v6 doc, but there was a huge burden for me to maintain with 6 languages.

**Comment by bluebill1049** [comment]
FYI merged this commit: https://github.com/react-hook-form/documentation/pull/941 hopefully not getting too much hustle for you.

**Comment by bluebill1049** [comment]
Perhaps we can release the first version without the i18n. I think it would already been a huge win for us.

**Comment by aranlucas** [comment]
> Perhaps we can release the first version without the i18n. I think it would already been a huge win for us.

Agree. Splitting it up into 3 parts to make this migration easier and less error prone

1. Running codemods. https://github.com/react-hook-form/documentation/pull/943/commits
2. Removing current language/ default language + fixing ALL TS errors (This way I don't need to disable it in next build :) )-> I have it ready but will wait for step-1.
3. Moving to nextjs. Smaller things like removing gatsby imports, adding new router, adding next-theme (Probably not modifying CSS files, still haven't been able to get that working)

Hopefully these smaller steps will lead to a more confident merge.

**Comment by aranlucas** [comment]
Closing this one since the better PR was merged :)

**Pull request closed without merging**
