### PR TITLE
Add video link for youtube playlist

### PR DESCRIPTION
**Pull request by vladnicula**
Adding a link to the playlist of the videos I've recently released. 

More videos will follow in the playlist I linked.

I'm not sure about the creation date. Or the timezone. Is that generated somehow?

### CODE REVIEW

**Review by bluebill1049 — APPROVED** [review]
LGTM. 👍

**Comment by bluebill1049** [comment]
oops just saw a mistake...
Screenshot 2023-01-28 at 3 01 43 pm

could you mark it as v7?

**Comment by bluebill1049** [comment]
Fixed.

**Comment by vladnicula** [comment]
thank you!

**Pull request merged**
