### PR TITLE
ts.tsx more accurate JP translation.

### PR DESCRIPTION
**Pull request by kyo8300**
I think the Japanese *TS Support* page was grammatically strange, so I updated src/data/jp/ts.tsx file.　

Thanks  :blush:

### CODE REVIEW

**Comment by pmaier983** [comment]
@keiya01 Hey Keiya any chance you could take a look at this PR? (no worries if not, it LGTM just wanted to be sure)

**Comment by bluebill1049** [comment]
Thank you! I thin i did google translate... 🥺

**Comment by bluebill1049** [comment]
> @keiya01 Hey Keiya any chance you could take a look at this PR? (no worries if not, it LGTM just wanted to be sure)

oops i miss the message above... feel free to adjust @keiya01 🙏

**Comment by keiya01** [comment]
That looks good :)

**Pull request merged**
