### PR TITLE
Added my article information resource

### PR DESCRIPTION
**Pull request by Kvaibhav01**
Published on daily.dev.

### CODE REVIEW

**Comment by bluebill1049** [comment]
thank you ❤️

**Comment by Kvaibhav01** [comment]
Thanks to you guys for this wonderful library and the quick response! 🤗

**Comment by bluebill1049** [comment]
> Thanks to you guys for this wonderful library and the quick response! 🤗

no worries, thank you for your article too. V7 is coming soon. hopefully you find it even more performant and powerful.

**Comment by Kvaibhav01** [comment]
Yes, waiting!! And I might write on how to migrate or use new features. 😊

**Pull request merged**
