### PR TITLE
Basic lighthouse setup

### PR DESCRIPTION
**Pull request by pmaier983**
This is the most basic setup for [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci). It runs a lighthouse check, creates a temporary report (saved for 7 days), and ensures the first-contentful-paint is not any slower then 2.5s.
To add in the future:
	- More assertions (They have a list of [recommended assertions](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#add-assertions) but I want to get the base setup working before adding more.
	- [nice configuration](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#github-status-checks) with github 
	- Create [our own server](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#the-lighthouse-ci-server) to check lighthouse stats. This would be awesome, but would require some careful setup. I'll leave it to last.

Question: Is there a way to test that this will work before merging the PR? Idk if it will trigger a actions run when i submit the PR. To be seen I guess.

### CODE REVIEW

**Comment by bluebill1049** [comment]
nice! i think it only work under 12 :(

**Comment by pmaier983** [comment]
Sorry, I don't use nvm so I sometimes accidentally change the node version :/

**Comment by pmaier983** [comment]
I'm going to wait till the morning to merge, so I can handle things if stuff doesn't work. Night 🌔 😊

**Comment by cpprookie** [comment]
> I'm going to wait till the morning to merge, so I can handle things if stuff doesn't work. Night 🌔 😊

Goodnight from shanghai  :)

**Comment by bluebill1049** [comment]
> > I'm going to wait till the morning to merge, so I can handle things if stuff doesn't work. Night 🌔 😊
> 
> Goodnight from shanghai :)

LOL same here :)

**Pull request merged**
