### PR TITLE
Proposal: to new way to make FAQ page

### PR DESCRIPTION
**Pull request by AdaltonLeite**
## description

I create a new way to build a FAQ page, it's more simple and prevent bug when we remove link questions. 

- Use map to render our questions and add a `<CodeArea ... />` inside a faq json. 
- Use a REMOVE_QUESTIONS_FOR_LIST variable to say how much questions we need to remove on render. 
- Create a new example code file to question **Why is the first keystroke not working?** before this code is inline on project.

## Bug fix.

This new implementation  fix a issue on FAQ page on production. We have a question that doesn’ t appear on sidebar menu.  Now the sidebar menu and questions is linked if appear on menu appear on question view. 

Captura de Tela 2022-10-25 às 21 50 28

### CODE REVIEW

**Comment by AdaltonLeite** [comment]
@bluebill1049 I closed the last PR and create this new.

**Comment by AdaltonLeite** [comment]
@bluebill1049 I updated a node version on lighthouse pipeline, they required a node 14.x and we use 12.x

**Comment by bluebill1049** [comment]
Oh wow nice 😊 thank you so much for the fix and contribution!

**Review by bluebill1049 — APPROVED** [review]
Awesome 😎 thanks again!

**Comment by AdaltonLeite** [comment]
Thank's @bluebill1049

**Pull request merged**
