### PR TITLE
feat: adding form and getFieldState to mdx

### PR DESCRIPTION
**Pull request by aranlucas**
Adding getFieldState + form MDX files

I'm still not super happy with the inline code but this will unblock some moving tables with code.

Missing 6 more pages to migrate to MDX
* formstate
* register
* usecontroller

* usefieldarray
* useformstate

### CODE REVIEW

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
Screenshot 2023-07-08 at 6 34 22 pm
crashed

**Review by bluebill1049 — CHANGES_REQUESTED** [review]
route is broken.

**Comment by aranlucas** [comment]
The root cause is the sidebar is not being resolved. I'm interested in why it's happening now since this change doesn't seem to have anything that could affect that, but I have a local change to fix it

**Comment by aranlucas** [comment]
There seems to have been 2 issues.

* SideMenu showing up null
* git file naming casing. I changed it locally to be lowercase and it worked as expected, but git doesn't detect those types of changes 😞 

```javascript
  const doc = allDocs.find(
    (doc) => doc._raw.flattenedPath === params?.slug?.join("/")
  )
```

**Review by bluebill1049 — APPROVED** [review]
Awesome thanks 👍

**Pull request merged**
